#!/usr/bin/env node
// A shared warehouse floor with robots from two operators. 40 totes each go pick station ->
// mobile robot -> sorter -> mobile robot -> pack station. Every receiving robot signs for the
// tote and pays the robot that delivered it, a fixed 3 cents per hop. One of botco's mobile
// robots loses its link for 20 minutes, keeps signing, and catches up when it reconnects. One
// tote never reaches packing. All data here is generated by the demo.
//   node demo.mjs
import { genKeypair } from "./lib/keys.mjs";
import { signRecord, contentOf, registry } from "./lib/record.mjs";
import { handoff, payment, gap } from "./src/records.mjs";
import { verifyTrail, verifyPayments, verifyOffline } from "./src/verify.mjs";

const SEC = 1000, MIN = 60 * SEC, T0 = Date.parse("2026-10-06T08:00:00Z"), RATE = 3;
const ts = (t) => new Date(t).toISOString().slice(11, 19);

const fleet = [
  ["pick-1", "acme"], ["acme-amr-1", "acme"], ["acme-amr-2", "acme"], ["sorter-1", "acme"],
  ["botco-amr-1", "botco"], ["botco-amr-2", "botco"], ["pack-1", "botco"],
].map(([id, operator]) => ({ id, operator, kp: genKeypair() }));
const kp = Object.fromEntries(fleet.map((r) => [r.id, r.kp]));
const STOLEN_AT = T0 + 3 * 60 * MIN;
const robots = registry(fleet.map((r) => ({ id: r.id, pub: r.kp.pub, operator: r.operator, ...(r.id === "acme-amr-2" ? { revokedAt: STOLEN_AT } : {}) })));

const trails = new Map(), handoffs = [], payments = [];
const OFF = [T0 + 30 * MIN, T0 + 50 * MIN];                    // botco-amr-2 offline
const hop = (item, from, to, at) => {
  const t = trails.get(item) || [];
  const h = handoff(kp[to], { itemId: item, from, to, at, prev: t.at(-1)?.claimId ?? null });
  trails.set(item, [...t, h]);
  handoffs.push(h);
  if (from !== "inbound") payments.push(payment(kp[to], { handoffId: h.claimId, payer: to, payee: from, at, amountCents: RATE, settlementRef: `ch-${h.claimId.slice(2, 14)}` }));
};
for (let i = 0; i < 40; i++) {
  const item = `TOTE-${String(i + 1).padStart(4, "0")}`, t = T0 + i * 90 * SEC;
  const amrIn = i % 2 ? "acme-amr-1" : "acme-amr-2", amrOut = i % 2 ? "botco-amr-1" : "botco-amr-2";
  hop(item, "inbound", "pick-1", t);
  hop(item, "pick-1", amrIn, t + 20 * SEC);
  hop(item, amrIn, "sorter-1", t + 80 * SEC);
  hop(item, "sorter-1", amrOut, t + 110 * SEC);
  if (item !== "TOTE-0031") hop(item, amrOut, "pack-1", t + 170 * SEC);
}
// Records botco-amr-2 signed while offline, in the order it signed them.
const offline = [...handoffs, ...payments].filter((r) => r.at >= OFF[0] && r.at <= OFF[1] && r.signerPub === kp["botco-amr-2"].pub);
const g = gap(kp["botco-amr-2"], { robot: "botco-amr-2", from: OFF[0], to: OFF[1], records: offline });

console.log(`${fleet.length} robots from 2 operators, ${trails.size} totes, ${handoffs.length} signed handoffs, ${payments.length} payments at ${RATE} cents per hop`);
const results = [...trails].map(([id, t]) => verifyTrail(id, t, { robots }));
console.log(`Every tote's trail verified: ${results.every((r) => r.ok) ? "PASS" : "FAIL"}`);
const notPacked = results.filter((r) => r.holder !== "pack-1");
for (const r of notPacked) console.log(`  ${r.itemId} not packed. Last signed for by ${r.holder} (operator ${r.operator}), ${ts(trails.get(r.itemId).at(-1).at)} UTC: that operator answers for it`);

const off = verifyOffline(g, [...handoffs, ...payments], { robots });
console.log(`botco-amr-2 offline ${ts(OFF[0])} to ${ts(OFF[1])}: ${off.ok ? `${off.records} records signed meanwhile, all accounted for by its catch-up record` : off.reason}`);

const pay = verifyPayments(handoffs, payments, { robots, expectedCents: RATE });
console.log(`Payments verified: ${pay.ok ? "PASS" : "FAIL"}, ${pay.accepted} bound to handoffs, ${pay.unpaid.length} unpaid`);

console.log("\nTampering:");
const say = (label, r) => console.log(`  ${label.padEnd(60)} ${r.ok ? "NOT CAUGHT" : "caught: " + [...new Set((r.problems || [{ reason: r.reason }]).map((x) => x.reason))].join(", ")}`);
const t31 = trails.get("TOTE-0031");
say("botco-amr-2 claims it handed TOTE-0031 to packing", verifyTrail("TOTE-0031", [...t31, handoff(kp["botco-amr-2"], { itemId: "TOTE-0031", from: "botco-amr-2", to: "pack-1", at: t31.at(-1).at + MIN, prev: t31.at(-1).claimId })], { robots }));
say("sorter's handoff removed from a trail", verifyTrail("TOTE-0002", trails.get("TOTE-0002").filter((h) => h.to !== "sorter-1"), { robots }));
say("handoff signed with acme-amr-2's key after it was revoked", verifyTrail("TOTE-0099", [handoff(kp["acme-amr-2"], { itemId: "TOTE-0099", from: "inbound", to: "acme-amr-2", at: STOLEN_AT + MIN })], { robots }));
say("botco-amr-1 bills the same handoff twice", verifyPayments(handoffs, [...payments, payments.find((p) => p.payee === "botco-amr-1")], { robots, expectedCents: RATE }));
say("pack-1 pays for a handoff that never happened", verifyPayments(handoffs, [...payments, payment(kp["pack-1"], { handoffId: "0x" + "ab".repeat(32), payer: "pack-1", payee: "botco-amr-2", at: T0, amountCents: RATE, settlementRef: "x" })], { robots, expectedCents: RATE }));
say("a payment's amount raised from 3 to 30 cents", verifyPayments(handoffs, payments.map((p, i) => (i === 5 ? signRecord(kp[p.payer], { ...contentOf(p), amountCents: 30 }) : p)), { robots, expectedCents: RATE }));
say("a record withheld from botco-amr-2's offline period", verifyOffline(g, [...handoffs, ...payments].filter((r) => r.claimId !== offline[2].claimId), { robots }));
say("a record added to botco-amr-2's offline period afterwards", verifyOffline(g, [...handoffs, ...payments, handoff(kp["botco-amr-2"], { itemId: "TOTE-9999", from: "sorter-1", to: "botco-amr-2", at: OFF[0] + MIN })], { robots }));
